package pkg

import (
	_ "embed"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"text/template"

	"github.com/typstify/tpix-cli/api"
	"github.com/typstify/tpix-cli/bundler"
	"looz.ws/typstify/typst"
)

var (
	//go:embed typst.toml
	manifestTemplate []byte
)

const (
	entrypointFile = `// This file is the entrypoint of your package. Generated by Typstify.`
)

// Scan the local dir to find typst packages.
//
// The pkgDir layout should have 3 layer hierarchies:
// 1. namespace folders
// 2. package folders
// 3. version folders
// The returned data holds the same 3 layer mapping.
func scanPackages(pkgDir string) (map[string]map[string]TypstPkg, error) {
	pkgMap := make(map[string]map[string]TypstPkg)

	// Read namespaces.
	entries, err := os.ReadDir(pkgDir)
	if err != nil {
		return pkgMap, err
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			// Not a namespace dir
			continue
		}
		namespace := entry.Name()
		if _, ok := pkgMap[namespace]; !ok {
			pkgMap[namespace] = make(map[string]TypstPkg)
		}

		// read packages
		pkgEntries, err := os.ReadDir(filepath.Join(pkgDir, namespace))
		if err != nil {
			log.Println("scan package error: ", err)
			continue
		}

		for _, pkgEntry := range pkgEntries {
			if !pkgEntry.IsDir() {
				// Not a package dir
				continue
			}
			packageName := pkgEntry.Name()
			// read versions
			verEntries, err := os.ReadDir(filepath.Join(pkgDir, namespace, packageName))
			if err != nil {
				log.Println("scan package error: ", err)
				continue
			}

			for _, verEntry := range verEntries {
				if !verEntry.IsDir() {
					// not a version dir
					continue
				}
				version := verEntry.Name()
				metaFile, err := os.Open(filepath.Join(pkgDir, namespace, packageName, version, "typst.toml"))
				if err != nil {
					log.Println("scan package error: ", err)
					continue
				}

				metadata, err := io.ReadAll(metaFile)
				if err != nil {
					log.Println("read package metadata error: ", err)
					continue
				}

				var pkgInfo bundler.Manifest
				err = bundler.DecodeBytes(metadata, &pkgInfo)
				if err != nil {
					log.Printf("scan package %s error: %v", filepath.Join(pkgDir, namespace, packageName, version), err)
					continue
				}

				// add to the final pkgMap
				p, ok := pkgMap[namespace][packageName]
				if !ok {
					p = TypstPkg{
						IsCached: true,
						SearchResult: api.SearchResult{
							Namespace:   namespace,
							Name:        pkgInfo.Package.Name,
							Description: pkgInfo.Package.Description,
							License:     pkgInfo.Package.License,
							IsTemplate:  pkgInfo.Template != nil,
							Authors:     pkgInfo.Package.Authors,
							Categories:  pkgInfo.Package.Categories,
							Disciplines: pkgInfo.Package.Disciplines,
						},
					}
				}

				p.Versions = append(p.Versions, api.PackageVersionInfo{
					Version: pkgInfo.Package.Version,
					Meta:    pkgInfo,
				})

				pkgMap[namespace][packageName] = p

			}
		}
	}

	return pkgMap, nil
}

func CreatePkg(pkgDir string, name string, isTemplate bool) (string, error) {
	if name == "" {
		return "", errors.New("invalid package name")
	}

	manifest := bundler.Manifest{
		Package: &bundler.Package{
			Name:        name,
			Version:     "0.1.0",
			Entrypoint:  "lib.typ",
			Authors:     []string{""},
			License:     "",
			Description: "An example package.",
			Homepage:    "",
			Repository:  "",
			Compiler:    typst.CurrentVersion(),
		},
	}

	if isTemplate {
		manifest.Template = &bundler.Template{
			Path:       "template",
			Entrypoint: "main.typ",
			Thumbnail:  "thumbnail.png", // Make sure user have a thumbnail.
		}
	}

	pkgDir = filepath.Join(pkgDir, name)
	err := os.MkdirAll(pkgDir, 0755)
	if err != nil {
		return "", err
	}

	// generate manifest file

	err = generateManifest(manifest, pkgDir)
	if err != nil {
		return "", err
	}

	// create entrypoint file
	err = createTemplateFile(filepath.Join(pkgDir, "lib.typ"), entrypointFile)
	if err != nil {
		return "", err
	}
	err = createTemplateFile(filepath.Join(pkgDir, "LICENSE"), "Put your license text here.")
	if err != nil {
		return "", err
	}

	err = createTemplateFile(filepath.Join(pkgDir, "README.md"), "This is a sample readme file.")
	if err != nil {
		return "", err
	}

	if isTemplate {
		err = createTemplateFile(filepath.Join(pkgDir, "template", "main.typ"), entrypointFile)
		if err != nil {
			return "", err
		}
	}

	return pkgDir, nil
}

func createTemplateFile(path string, content string) error {
	if fileExists(path) {
		return nil
	}

	err := os.MkdirAll(filepath.Dir(path), 0755)
	if err != nil {
		return err
	}

	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0755)
	if err != nil {
		return err
	}

	defer file.Close()

	_, err = file.WriteString(content)
	return err
}

func generateManifest(manifest bundler.Manifest, dir string) error {
	dest := filepath.Join(dir, "typst.toml")
	if fileExists(dest) {
		return nil
	}

	file, err := os.OpenFile(dest, os.O_CREATE|os.O_WRONLY, 0755)
	if err != nil {
		return err
	}

	defer file.Close()

	tmpl, err := template.New("typstPkgManifestTmpl").Parse(string(manifestTemplate))
	if err != nil {
		panic("Invalid manifest template")
	}

	return tmpl.Execute(file, manifest)
}

func fileExists(path string) bool {
	st, err := os.Stat(path)
	return !errors.Is(err, os.ErrNotExist) && !st.IsDir()
}

const readme = `
This is a sample README file for %s.

These files are generated by Typstify for you:

1. typst.toml: A Typst package manifest. Useful if you want to convert your project to a Typst package. Remove it if you don't need it.
2. LICENSE: An empty license statement file.
3. README.md: This file you are reading now.
4. main.typ: An entrypoint file for your document.

Feel free to edit or remove the above files.
`

func createTemplateDocument(packageDir string, name string) (string, error) {
	if packageDir == "" {
		return "", errors.New("invalid package dir")
	}

	manifest := bundler.Manifest{
		Package: &bundler.Package{
			Name:        name,
			Version:     "0.1.0",
			Entrypoint:  "main.typ",
			Authors:     []string{""},
			License:     "",
			Description: "An example Typst document project.",
			Homepage:    "",
			Repository:  "",
			Compiler:    typst.CurrentVersion(),
		},
	}

	pkgDir := filepath.Join(packageDir, name)
	err := os.MkdirAll(pkgDir, 0755)
	if err != nil {
		return pkgDir, err
	}

	// generate manifest file
	err = generateManifest(manifest, pkgDir)
	if err != nil {
		return pkgDir, err
	}

	// create entrypoint file
	err = createTemplateFile(filepath.Join(pkgDir, "main.typ"), entrypointFile)
	if err != nil {
		return pkgDir, err
	}
	err = createTemplateFile(filepath.Join(pkgDir, "LICENSE"), "Put your license text here.")
	if err != nil {
		return pkgDir, err
	}

	err = createTemplateFile(filepath.Join(pkgDir, "README.md"), fmt.Sprintf(readme, name))
	if err != nil {
		return pkgDir, err
	}

	return pkgDir, nil
}
