package pkg

import (
	"cmp"
	"errors"
	"os"
	"path/filepath"
	"slices"

	"looz.ws/typstify/typst"
)

const (
	entrypointFile = `// This file is the entrypoint of your package. Generated by Typstify.`
)

type localPkgRepo struct {
	pkgDir string
}

func (tp *localPkgRepo) ListPkgs() ([]*TypstPkg, error) {
	pkgMap, err := scanPackages(tp.pkgDir, false)
	if err != nil {
		return nil, err
	}

	list := make([]*TypstPkg, 0)
	for _, p := range pkgMap {
		for _, v := range p {
			list = append(list, v)
		}
	}
	slices.SortStableFunc(list, func(a, b *TypstPkg) int { return cmp.Compare(a.Name, b.Name) })

	return list, nil
}

func (tp *localPkgRepo) CreatePkg(name string, namespace string, isTemplate bool) (string, error) {
	if namespace == "" {
		namespace = "local"
	}

	if name == "" {
		return "", errors.New("invalid package name")
	}

	manifest := Package{
		Name:        name,
		Version:     "0.1.0",
		Entrypoint:  "lib.typ",
		Authors:     []string{""},
		License:     "",
		Description: "An example package.",
		Homepage:    "",
		Repository:  "",
		Compiler:    typst.CurrentVersion(),
	}

	if isTemplate {
		manifest.Template = &TemplateInfo{
			Path:       "template",
			Entrypoint: "main.typ",
			Thumbnail:  "thumbnail.png",
		}
	}

	pkgDir := filepath.Join(tp.pkgDir, namespace, name)
	dir := filepath.Join(pkgDir, manifest.Version)
	err := os.MkdirAll(dir, 0755)
	if err != nil {
		return pkgDir, err
	}

	// generate manifest file

	err = GenerateManifest(&manifest, dir)
	if err != nil {
		return pkgDir, err
	}

	// create entrypoint file
	err = createTemplateFile(filepath.Join(dir, "lib.typ"), entrypointFile)
	if err != nil {
		return pkgDir, err
	}
	err = createTemplateFile(filepath.Join(dir, "LICENSE"), "Put your license text here.")
	if err != nil {
		return pkgDir, err
	}

	err = createTemplateFile(filepath.Join(dir, "README.md"), "This is a sample readme file.")
	if err != nil {
		return pkgDir, err
	}

	if isTemplate {
		err = createTemplateFile(filepath.Join(dir, "template", "main.typ"), entrypointFile)
		if err != nil {
			return pkgDir, err
		}
	}

	return pkgDir, nil
}

func createTemplateFile(path string, content string) error {
	if fileExists(path) {
		return nil
	}

	err := os.MkdirAll(filepath.Dir(path), 0755)
	if err != nil {
		return err
	}

	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0755)
	if err != nil {
		return err
	}

	defer file.Close()

	_, err = file.WriteString(content)
	return err
}
